// =============================================================================
// emailService.js
// Mock email receipt sender.
// Replace sendReceiptEmail() with real SendGrid/Resend/nodemailer call later.
// =============================================================================

/** In-memory mock outbox for testing / inspection */
export const mockOutbox = [];

/**
 * Formats a receipt as a human-readable text "email body".
 * @param {Object} receipt — generated by generateReceipt()
 * @returns {string}
 */
function formatReceiptEmail(receipt) {
  const lines = [
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `   SOCIETY MAINTENANCE RECEIPT`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `Transaction ID : ${receipt.transactionId}`,
    `Payment Date   : ${new Date(receipt.paymentDate).toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' })}`,
    ``,
    `Resident       : ${receipt.payerName}`,
    `Email          : ${receipt.payerEmail || 'N/A'}`,
    `Unit / Flat    : ${receipt.unitLabel}`,
    `Month(s) Paid  : ${receipt.months.join(', ')}`,
    ``,
    `Base Amount    : ₹ ${receipt.baseAmount.toFixed(2)}`,
    receipt.penalty > 0
      ? `Late Penalty   : ₹ ${receipt.penalty.toFixed(2)}`
      : null,
    `──────────────────────────────────`,
    `Total Paid     : ₹ ${receipt.totalAmount.toFixed(2)}`,
    `Payment Method : ${receipt.paymentMethod}`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `Thank you for keeping maintenance current!`,
  ]
    .filter(Boolean)
    .join('\n');
  return lines;
}

/**
 * Sends a receipt via email (mock implementation).
 *
 * In production: replace the console.log + outbox push with your real
 * email provider call:
 *   await sendGrid.send({ to: receipt.payerEmail, subject, html });
 *
 * @param {Object} receipt — generated by generateReceipt()
 * @returns {Promise<{ sent: boolean, to: string }>}
 */
export async function sendReceiptEmail(receipt) {
  const emailBody = formatReceiptEmail(receipt);
  const emailPayload = {
    to: receipt.payerEmail || 'resident@example.com',
    subject: `[SecuriX] Payment Receipt — ${receipt.months.join(', ')} | ${receipt.transactionId}`,
    body: emailBody,
    receipt,
    sentAt: new Date().toISOString(),
  };

  // ── MOCK: log to console + store in outbox ──────────────────────────────
  console.group(`📧 [MockEmailService] Receipt Sent`);
  console.log(`To      : ${emailPayload.to}`);
  console.log(`Subject : ${emailPayload.subject}`);
  console.log(emailBody);
  console.groupEnd();

  mockOutbox.push(emailPayload);
  // ────────────────────────────────────────────────────────────────────────

  // Simulate network latency
  await new Promise((r) => setTimeout(r, 300));

  return { sent: true, to: emailPayload.to };
}
